You can think of each array as a seperate raster which shape = 3x3
By stacking each raster, you can get a single "pixels" value for each raster.
The rasters represent the dimensions of the stacked array. 

In [1]:
import numpy as np

# Set the seed for reproducibility
#np.random.seed(42)

# Create the 8 different 2D arrays
# first array is 3x3 with value of 08001
fips = np.full((3, 3), 108001, dtype=np.int32) # will need to change this to 08001
risk = np.zeros((3, 3), dtype=np.int32) # zeros will change during the risk calcualtion
levee = np.random.randint(1, 101, size=(3, 3), dtype=np.int32) # height in feet
cat1 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet
cat2 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet
cat3 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32)   # height in feet
cat4 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet
cat5 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet

print('fips')
print(fips)
print('____________________')
print('risk')
print(risk)
print('____________________')
print('levee')
print(levee)
print('____________________')
print('cat1')
print(cat1)
print('____________________')
print('cat2')
print(cat2)
print('____________________')
print('cat3')
print(cat3)
print('____________________')
print('cat4')
print(cat4)
print('____________________')  
print('cat5')
print(cat5)

fips
[[108001 108001 108001]
 [108001 108001 108001]
 [108001 108001 108001]]
____________________
risk
[[0 0 0]
 [0 0 0]
 [0 0 0]]
____________________
levee
[[19 33 33]
 [68 92  9]
 [59 42 83]]
____________________
cat1
[[1 6 8]
 [0 8 3]
 [0 8 9]]
____________________
cat2
[[ 2  8  2]
 [ 9  8 10]
 [ 7  3  2]]
____________________
cat3
[[ 0  9  7]
 [10  7  3]
 [ 8  7 10]]
____________________
cat4
[[9 3 6]
 [2 2 8]
 [6 2 2]]
____________________
cat5
[[ 3  9  1]
 [10  2  8]
 [ 8  1  5]]


In [2]:
# stack the arrays in this shape: 8x3x3
df = np.stack((fips, risk, levee, cat1, cat2, cat3, cat4, cat5), axis=0)
df

array([[[108001, 108001, 108001],
        [108001, 108001, 108001],
        [108001, 108001, 108001]],

       [[     0,      0,      0],
        [     0,      0,      0],
        [     0,      0,      0]],

       [[    19,     33,     33],
        [    68,     92,      9],
        [    59,     42,     83]],

       [[     1,      6,      8],
        [     0,      8,      3],
        [     0,      8,      9]],

       [[     2,      8,      2],
        [     9,      8,     10],
        [     7,      3,      2]],

       [[     0,      9,      7],
        [    10,      7,      3],
        [     8,      7,     10]],

       [[     9,      3,      6],
        [     2,      2,      8],
        [     6,      2,      2]],

       [[     3,      9,      1],
        [    10,      2,      8],
        [     8,      1,      5]]])

In [3]:
df.shape

(8, 3, 3)

In [5]:
# give me all the dimension values at pixel 0,0 
df[:, 0, 0]

array([108001,      0,      3,      7,     10,      2,      2,      1])

In [6]:
# Ensure values are ascending across layers at the same position
shape = df.shape
print(shape)
for row in range(shape[1]): # For each row
    #print(f'row:{row}')
    for col in range(shape[2]): # For each column
        #print(f'col:{col}')
        for layer in range(5, shape[0]): # For each cat after the first
            #print(f'cat:{layer}')
            if df[layer, row, col] <= df[layer - 1, row, col]:
                df[layer, row, col] = df[layer - 1, row, col] + 1

df

(8, 3, 3)


array([[[108001, 108001, 108001],
        [108001, 108001, 108001],
        [108001, 108001, 108001]],

       [[     0,      0,      0],
        [     0,      0,      0],
        [     0,      0,      0]],

       [[     3,    100,     67],
        [    72,     62,     94],
        [    44,     44,     81]],

       [[     7,      0,      3],
        [     0,      7,      0],
        [     8,      3,      7]],

       [[    10,      7,      1],
        [     7,      9,      4],
        [     3,      7,      1]],

       [[    11,      8,      3],
        [     8,     10,      6],
        [     4,      8,      8]],

       [[    12,      9,      9],
        [     9,     11,      7],
        [    10,      9,     10]],

       [[    13,     10,     10],
        [    10,     12,      8],
        [    11,     10,     11]]])