You can think of each array as a seperate raster which shape = 3x3
By stacking each raster, you can get a single "pixels" value for each raster.
The rasters represent the dimensions of the stacked array. 

In [3]:
import numpy as np

# Set the seed for reproducibility
#np.random.seed(42)

# Create the 8 different 2D arrays
# first array is 3x3 with value of 08001
fips = np.full((3, 3), 108001, dtype=np.int32) # will need to change this to 08001
risk = np.zeros((3, 3), dtype=np.int32) # zeros will change during the risk calcualtion
levee = np.random.randint(1, 101, size=(3, 3), dtype=np.int32) # height in feet
cat1 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet
cat2 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet
cat3 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32)   # height in feet
cat4 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet
cat5 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet

print('fips')
print(fips)
print('____________________')
print('risk')
print(risk)
print('____________________')
print('levee')
print(levee)
print('____________________')
print('cat1')
print(cat1)
print('____________________')
print('cat2')
print(cat2)
print('____________________')
print('cat3')
print(cat3)
print('____________________')
print('cat4')
print(cat4)
print('____________________')  
print('cat5')
print(cat5)

fips
[[108001 108001 108001]
 [108001 108001 108001]
 [108001 108001 108001]]
____________________
risk
[[0 0 0]
 [0 0 0]
 [0 0 0]]
____________________
levee
[[  3 100  67]
 [ 72  62  94]
 [ 44  44  81]]
____________________
cat1
[[7 0 3]
 [0 7 0]
 [8 3 7]]
____________________
cat2
[[10  7  1]
 [ 7  9  4]
 [ 3  7  1]]
____________________
cat3
[[2 4 3]
 [4 1 6]
 [0 7 8]]
____________________
cat4
[[ 2  4  9]
 [ 9  7  1]
 [10  3 10]]
____________________
cat5
[[ 1  7  3]
 [10  5  0]
 [ 1  2  4]]


In [4]:
# stack the arrays in this shape: 8x3x3
df = np.stack((fips, risk, levee, cat1, cat2, cat3, cat4, cat5), axis=0)
df

array([[[108001, 108001, 108001],
        [108001, 108001, 108001],
        [108001, 108001, 108001]],

       [[     0,      0,      0],
        [     0,      0,      0],
        [     0,      0,      0]],

       [[     3,    100,     67],
        [    72,     62,     94],
        [    44,     44,     81]],

       [[     7,      0,      3],
        [     0,      7,      0],
        [     8,      3,      7]],

       [[    10,      7,      1],
        [     7,      9,      4],
        [     3,      7,      1]],

       [[     2,      4,      3],
        [     4,      1,      6],
        [     0,      7,      8]],

       [[     2,      4,      9],
        [     9,      7,      1],
        [    10,      3,     10]],

       [[     1,      7,      3],
        [    10,      5,      0],
        [     1,      2,      4]]])

In [5]:
# give me all the dimension values at pixel 0,0 
df[:, 0, 0]

array([108001,      0,      3,      7,     10,      2,      2,      1])

In [6]:
# Ensure values are ascending across layers at the same position
shape = df.shape
print(shape)
for row in range(shape[1]): # For each row
    #print(f'row:{row}')
    for col in range(shape[2]): # For each column
        #print(f'col:{col}')
        for layer in range(5, shape[0]): # For each cat after the first
            #print(f'cat:{layer}')
            if df[layer, row, col] <= df[layer - 1, row, col]:
                df[layer, row, col] = df[layer - 1, row, col] + 1

df

(8, 3, 3)


array([[[108001, 108001, 108001],
        [108001, 108001, 108001],
        [108001, 108001, 108001]],

       [[     0,      0,      0],
        [     0,      0,      0],
        [     0,      0,      0]],

       [[     3,    100,     67],
        [    72,     62,     94],
        [    44,     44,     81]],

       [[     7,      0,      3],
        [     0,      7,      0],
        [     8,      3,      7]],

       [[    10,      7,      1],
        [     7,      9,      4],
        [     3,      7,      1]],

       [[    11,      8,      3],
        [     8,     10,      6],
        [     4,      8,      8]],

       [[    12,      9,      9],
        [     9,     11,      7],
        [    10,      9,     10]],

       [[    13,     10,     10],
        [    10,     12,      8],
        [    11,     10,     11]]])

In [ ]:
aaa

In [2]:
ds2 = gdal.Open('test_cat2.tif')
ds3 = gdal.Open('test_cat3.tif')

cat2 = ds2.ReadAsArray()
cat3 = ds3.ReadAsArray()

In [3]:
print(cat2.shape)
print(cat3.shape)

(11, 16)
(11, 16)


In [5]:
all_cats = np.array([cat2, cat3])

In [6]:
all_cats

array([[[ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5]],

       [[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10,

In [9]:
shape = all_cats.shape
all_cats[0] # cat2
all_cats[1] # cat3

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]], dtype=uint8)