In [1]:
import math
import numpy as np

In [4]:


# Set the seed for reproducibility
#np.random.seed(42)

# Create the 8 different 2D arrays
# first array is 3x3 with value of 08001
fips = np.full((3, 3), 108001, dtype=np.int32) # will need to change this to 08001
risk = np.zeros((3, 3), dtype=np.int32) # zeros will change during the risk calcualtion
levee = np.random.randint(1, 101, size=(3, 3), dtype=np.int32) # height in feet
cat1 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet
cat2 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet
cat3 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32)   # height in feet
cat4 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet
cat5 = np.random.randint(0, 11, size=(3, 3), dtype=np.int32) # height in feet

print('fips')
print(fips)
print('____________________')
print('risk')
print(risk)
print('____________________')
print('levee')
print(levee)
print('____________________')
print('cat1')
print(cat1)
print('____________________')
print('cat2')
print(cat2)
print('____________________')
print('cat3')
print(cat3)
print('____________________')
print('cat4')
print(cat4)
print('____________________')  
print('cat5')
print(cat5)

fips
[[108001 108001 108001]
 [108001 108001 108001]
 [108001 108001 108001]]
____________________
risk
[[0 0 0]
 [0 0 0]
 [0 0 0]]
____________________
levee
[[95 82 97]
 [20 13 32]
 [82 99 80]]
____________________
cat1
[[5 6 4]
 [8 0 5]
 [0 7 0]]
____________________
cat2
[[ 8 10  6]
 [ 0  6  5]
 [ 8  7  9]]
____________________
cat3
[[5 2 7]
 [0 3 3]
 [2 3 0]]
____________________
cat4
[[ 5  9  3]
 [10  0  9]
 [10  0  9]]
____________________
cat5
[[ 8  1 10]
 [ 2  1  4]
 [ 8  5  0]]


In [5]:
# convert all the arrays to float
cat1 = cat1.astype(np.float32)
cat2 = cat2.astype(np.float32)
cat3 = cat3.astype(np.float32)
cat4 = cat4.astype(np.float32)
cat5 = cat5.astype(np.float32)

print('____________________')
print('cat1')
print(cat1)
print('____________________')
print('cat2')
print(cat2)
print('____________________')
print('cat3')
print(cat3)
print('____________________')
print('cat4')
print(cat4)
print('____________________')
print('cat5')
print(cat5)

____________________
cat1
[[5. 6. 4.]
 [8. 0. 5.]
 [0. 7. 0.]]
____________________
cat2
[[ 8. 10.  6.]
 [ 0.  6.  5.]
 [ 8.  7.  9.]]
____________________
cat3
[[5. 2. 7.]
 [0. 3. 3.]
 [2. 3. 0.]]
____________________
cat4
[[ 5.  9.  3.]
 [10.  0.  9.]
 [10.  0.  9.]]
____________________
cat5
[[ 8.  1. 10.]
 [ 2.  1.  4.]
 [ 8.  5.  0.]]


In [10]:
def convert_nodata(arr):
    arr[arr == 0] = -1
    return arr

cat1 = convert_nodata(cat1) 
cat2 = convert_nodata(cat2)
cat3 = convert_nodata(cat3)
cat4 = convert_nodata(cat4) 
cat5 = convert_nodata(cat5)

print(cat1)
print('____________________')
print(cat2)
print('____________________')
print(cat3)
print('____________________')
print(cat4)
print('____________________')
print(cat5)


[[ 5.  6.  4.]
 [ 8. -1.  5.]
 [-1.  7. -1.]]
____________________
[[ 8. 10.  6.]
 [-1.  6.  5.]
 [ 8.  7.  9.]]
____________________
[[ 5.  2.  7.]
 [-1.  3.  3.]
 [ 2.  3. -1.]]
____________________
[[ 5.  9.  3.]
 [10. -1.  9.]
 [10. -1.  9.]]
____________________
[[ 8.  1. 10.]
 [ 2.  1.  4.]
 [ 8.  5. -1.]]


In [12]:
#  subtract cat1 from cat2 where element is -1
cat12 = np.where((cat1 == -1) | (cat2 != -1), cat2 - cat1, cat2)
cat12

array([[ 3.,  4.,  2.],
       [-1.,  7.,  0.],
       [ 9.,  0., 10.]], dtype=float32)

In [13]:
np.ma.masked_where(cat12 == -1, cat12)

masked_array(
  data=[[3.0, 4.0, 2.0],
        [--, 7.0, 0.0],
        [9.0, 0.0, 10.0]],
  mask=[[False, False, False],
        [ True, False, False],
        [False, False, False]],
  fill_value=1e+20,
  dtype=float32)

In [17]:
11/1000

0.011

In [14]:
CAT1_SLOT = 10 # first slot after decimal
CAT2_SLOT = 100 # second slot after decimal
CAT3_SLOT = 1000 # third slot after decimal
CAT4_SLOT = 10000 # fourth slot after decimal
CAT5_SLOT = 100000 # fifth slot after decimal

cat12_nodata_mask = np.ma.masked_where(cat12 == -1, cat12)
main_arr = np.where(cat2 < cat12_nodata_mask, np.round(2+(0 + cat2/CAT2_SLOT), 5), np.round(1+(cat1/CAT1_SLOT + cat2/CAT2_SLOT),5))

print(main_arr)

[[1.58 1.7  1.46]
 [1.79 2.06 1.55]
 [2.08 1.77 2.09]]


In [37]:
print(cat1)
print('____________________')
print(cat2)
print('____________________')
print(cat3)
print('____________________')
print(cat4)
print('____________________')
print(cat5)

[[ 3.  1.  7.]
 [ 8. -1.  6.]
 [ 6. -1.  6.]]
____________________
[[6. 5. 8.]
 [9. 1. 1.]
 [5. 3. 7.]]
____________________
[[ 7. 10.  9.]
 [ 4.  5.  3.]
 [ 6.  7. -1.]]
____________________
[[4. 3. 9.]
 [7. 5. 8.]
 [5. 8. 7.]]
____________________
[[ 2.  3.  5.]
 [ 7.  3.  8.]
 [ 5. 10.  4.]]


In [4]:
# stack the arrays in this shape: 8x3x3
df = np.stack((fips, risk, levee, cat1, cat2, cat3, cat4, cat5), axis=0)
df

array([[[108001, 108001, 108001],
        [108001, 108001, 108001],
        [108001, 108001, 108001]],

       [[     0,      0,      0],
        [     0,      0,      0],
        [     0,      0,      0]],

       [[     3,    100,     67],
        [    72,     62,     94],
        [    44,     44,     81]],

       [[     7,      0,      3],
        [     0,      7,      0],
        [     8,      3,      7]],

       [[    10,      7,      1],
        [     7,      9,      4],
        [     3,      7,      1]],

       [[     2,      4,      3],
        [     4,      1,      6],
        [     0,      7,      8]],

       [[     2,      4,      9],
        [     9,      7,      1],
        [    10,      3,     10]],

       [[     1,      7,      3],
        [    10,      5,      0],
        [     1,      2,      4]]])

In [5]:
# give me all the dimension values at pixel 0,0 
df[:, 0, 0]

array([108001,      0,      3,      7,     10,      2,      2,      1])

In [6]:
# Ensure values are ascending across layers at the same position
shape = df.shape
print(shape)
for row in range(shape[1]): # For each row
    #print(f'row:{row}')
    for col in range(shape[2]): # For each column
        #print(f'col:{col}')
        for layer in range(5, shape[0]): # For each cat after the first
            #print(f'cat:{layer}')
            if df[layer, row, col] <= df[layer - 1, row, col]:
                df[layer, row, col] = df[layer - 1, row, col] + 1

df

(8, 3, 3)


array([[[108001, 108001, 108001],
        [108001, 108001, 108001],
        [108001, 108001, 108001]],

       [[     0,      0,      0],
        [     0,      0,      0],
        [     0,      0,      0]],

       [[     3,    100,     67],
        [    72,     62,     94],
        [    44,     44,     81]],

       [[     7,      0,      3],
        [     0,      7,      0],
        [     8,      3,      7]],

       [[    10,      7,      1],
        [     7,      9,      4],
        [     3,      7,      1]],

       [[    11,      8,      3],
        [     8,     10,      6],
        [     4,      8,      8]],

       [[    12,      9,      9],
        [     9,     11,      7],
        [    10,      9,     10]],

       [[    13,     10,     10],
        [    10,     12,      8],
        [    11,     10,     11]]])