In [1]:
import numpy as np
import pandas as pd
from osgeo import gdal

In [35]:
arr = np.array([
    [ # cat 1
        [5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1]
    ],
    [ # cat 2
        [6, 1, 5, 7, 10],
        [10, 4, 6, 5, 6],
        [8, 8, 9, 9, 8]
    ],
    [ # cat 3
        [5, 2, 10, 8, 12],
        [11, 5, 7, 7, 8],
        [9, 9, 10, 11, 15]
    ]
])


In [36]:
# Ensure values are ascending across layers at the same position
shape = arr.shape
print(shape)
for row in range(shape[1]): # For each row
    #print(f'row:{row}')
    for col in range(shape[2]): # For each column
        #print(f'col:{col}')
        for layer in range(1, shape[0]): # For each cat after the first
            #print(f'cat:{layer}')
            if arr[layer, row, col] <= arr[layer - 1, row, col]:
                arr[layer, row, col] = arr[layer - 1, row, col] + 1

# Display the adjusted 3D array
print(arr)

(3, 3, 5)
[[[ 5  0  3  3  7]
  [ 9  3  5  2  4]
  [ 7  6  8  8  1]]

 [[ 6  1  5  7 10]
  [10  4  6  5  6]
  [ 8  8  9  9  8]]

 [[ 7  2 10  8 12]
  [11  5  7  7  8]
  [ 9  9 10 11 15]]]
